apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rss-serve-ingress
  labels:
    app: rss-serve
  annotations:
    kubernetes.io/ingress.class: cloudflare-tunnel
spec:
  rules:
    - host: feed.hugis.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rss-serve
                port:
                  number: 80