apiVersion: v1
kind: Service
metadata:
  name: rss-serve
  labels:
    app: rss-serve
  annotations:
    tunnel.cloudflare.com/ingress-hostname: feed.hugis.dev
spec:
  selector:
    app: rss-serve
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP